import type { IEndpoint } from './type/type';
export const endpoints: IEndpoint[] = [
  { endpoint: 'spacecraft', version: 'v2', title: 'Spacecraft' },
  { endpoint: 'company', version: 'v2', title: 'Company' },
  { endpoint: 'comicStrip', version: 'v1', title: 'Comic Strip' },
  { endpoint: 'videoRelease', version: 'v2', title: 'Video Release' },
  { endpoint: 'organization', version: 'v1', title: 'Organization' },
  { endpoint: 'soundtrack', version: 'v1', title: 'Soundtrack' },
  { endpoint: 'character', version: 'v1', title: 'Character' },
  { endpoint: 'performer', version: 'v2', title: 'Performer' },
  { endpoint: 'occupation', version: 'v2', title: 'Occupation' },
  { endpoint: 'literature', version: 'v1', title: 'Literature' },
  { endpoint: 'magazine', version: 'v1', title: 'Magazine' },
  { endpoint: 'animal', version: 'v1', title: 'Animal' },
  { endpoint: 'spacecraftClass', version: 'v3', title: 'Spacecraft Class' },
  { endpoint: 'comicCollection', version: 'v2', title: 'Comic Collection' },
  { endpoint: 'book', version: 'v2', title: 'Book' },
  { endpoint: 'staff', version: 'v2', title: 'Staff' },
  { endpoint: 'common', version: 'v1', title: 'Common' },
  { endpoint: 'title', version: 'v2', title: 'Title' },
  {
    endpoint: 'astronomicalObject',
    version: 'v2',
    title: 'Astronomical Object',
  },
  { endpoint: 'element', version: 'v2', title: 'Element' },
  { endpoint: 'location', version: 'v2', title: 'Location' },
  { endpoint: 'tradingCard', version: 'v1', title: 'Trading Card' },
  { endpoint: 'comics', version: 'v1', title: 'Comics' },
  { endpoint: 'tradingCardDeck', version: 'v1', title: 'Trading Card Deck' },
  { endpoint: 'magazineSeries', version: 'v1', title: 'Magazine Series' },
  { endpoint: 'videoGame', version: 'v1', title: 'Video Game' },
  { endpoint: 'technology', version: 'v2', title: 'Technology' },
  { endpoint: 'comicSeries', version: 'v1', title: 'Comic Series' },
  { endpoint: 'movie', version: 'v1', title: 'Movie' },
  { endpoint: 'weapon', version: 'v2', title: 'Weapon' },
  { endpoint: 'episode', version: 'v1', title: 'Episode' },
  { endpoint: 'season', version: 'v1', title: 'Season' },
  { endpoint: 'bookSeries', version: 'v1', title: 'Book Series' },
  { endpoint: 'conflict', version: 'v2', title: 'Conflict' },
  { endpoint: 'material', version: 'v1', title: 'Material' },
  { endpoint: 'species', version: 'v2', title: 'Species' },
  { endpoint: 'bookCollection', version: 'v1', title: 'Book Collection' },
  { endpoint: 'medicalCondition', version: 'v1', title: 'Medical Condition' },
  { endpoint: 'food', version: 'v1', title: 'Food' },
  { endpoint: 'tradingCardSet', version: 'v1', title: 'Trading Card Set' },
  { endpoint: 'series', version: 'v1', title: 'Series' },
];
